from datetime import datetime, timezone

from sqlalchemy import select
from sqlalchemy.orm import Session

from backend.app.models.contact import EmergencyContact
from backend.app.models.notification import Notification


# ============================================================
# NOTIFICATION CONTENT
# ============================================================

def build_location_url(
    latitude: float,
    longitude: float,
) -> str:
    return (
        "https://www.google.com/maps/search/"
        f"?api=1&query={latitude},{longitude}"
    )


def build_sms_message(
    user_name: str,
    district: str | None,
    risk_level: str | None,
    risk_score: float | None,
    latitude: float,
    longitude: float,
) -> str:

    risk_text = (
        f"{risk_level} ({risk_score:.1f}/100)"
        if risk_level is not None
        and risk_score is not None
        else "UNKNOWN"
    )

    district_text = district or "Unknown"

    location_url = build_location_url(
        latitude=latitude,
        longitude=longitude,
    )

    return (
        "🚨 SAFEHER SOS ALERT\n"
        f"{user_name} has activated an emergency SOS.\n"
        f"Location: {district_text}\n"
        f"Risk: {risk_text}\n"
        f"GPS: {latitude:.6f}, {longitude:.6f}\n"
        f"Location: {location_url}"
    )


def build_email_subject(
    user_name: str,
) -> str:

    return (
        f"🚨 SafeHer Emergency SOS Alert - "
        f"{user_name}"
    )


def build_email_message(
    user_name: str,
    district: str | None,
    risk_level: str | None,
    risk_score: float | None,
    latitude: float,
    longitude: float,
    accuracy: float | None = None,
    predicted_ipc: float | None = None,
    predicted_women_crimes: float | None = None,
) -> str:

    risk_text = (
        f"{risk_level} ({risk_score:.1f}/100)"
        if risk_level is not None
        and risk_score is not None
        else "UNKNOWN"
    )

    location_url = build_location_url(
        latitude=latitude,
        longitude=longitude,
    )

    accuracy_text = (
        f"{accuracy:.0f} metres"
        if accuracy is not None
        else "Unavailable"
    )

    ipc_text = (
        f"{predicted_ipc:.0f}"
        if predicted_ipc is not None
        else "Unavailable"
    )

    women_crime_text = (
        f"{predicted_women_crimes:.0f}"
        if predicted_women_crimes is not None
        else "Unavailable"
    )

    return f"""
SAFEHER EMERGENCY ALERT
=======================

An emergency SOS has been activated.

Person
-------
{user_name}

Location
--------
District: {district or "Unknown"}

GPS coordinates:
{latitude:.6f}, {longitude:.6f}

GPS accuracy:
±{accuracy_text}

Safety Assessment
-----------------
Risk level: {risk_text}

Predicted IPC:
{ipc_text}

Predicted women-related crime:
{women_crime_text}

Open Location
-------------
{location_url}

IMPORTANT
---------
Please contact the person immediately if possible.

If the situation appears life-threatening,
contact the appropriate emergency services.

This alert was generated by the SafeHer
emergency response system.
""".strip()


# ============================================================
# CONTACT RETRIEVAL
# ============================================================

def get_user_emergency_contacts(
    db: Session,
    user_id: str,
) -> list[EmergencyContact]:

    statement = (
        select(EmergencyContact)
        .where(
            EmergencyContact.user_id == user_id
        )
        .order_by(
            EmergencyContact.created_at.asc()
        )
    )

    return list(
        db.execute(statement)
        .scalars()
        .all()
    )


# ============================================================
# CREATE NOTIFICATION RECORD
# ============================================================

def create_notification_record(
    db: Session,
    sos_id: str,
    user_id: str,
    channel: str,
    recipient: str,
) -> Notification:

    channel = channel.strip().upper()

    allowed_channels = {
        "SMS",
        "EMAIL",
    }

    if channel not in allowed_channels:
        raise ValueError(
            "Unsupported notification channel."
        )

    notification = Notification(
        sos_id=sos_id,
        user_id=user_id,
        channel=channel,
        recipient=recipient,
        status="PENDING",
    )

    db.add(notification)

    try:
        db.commit()
        db.refresh(notification)

    except Exception:
        db.rollback()
        raise

    return notification


# ============================================================
# MARK NOTIFICATION SENT
# ============================================================

def mark_notification_sent(
    db: Session,
    notification_id: str,
    provider: str | None = None,
    provider_message_id: str | None = None,
) -> Notification | None:

    statement = (
        select(Notification)
        .where(
            Notification.id ==
            notification_id
        )
    )

    notification = (
        db.execute(statement)
        .scalar_one_or_none()
    )

    if notification is None:
        return None

    notification.status = "SENT"

    notification.provider = provider

    notification.provider_message_id = (
        provider_message_id
    )

    notification.error_message = None

    notification.sent_at = (
        datetime.now(timezone.utc)
    )

    notification.updated_at = (
        datetime.now(timezone.utc)
    )

    try:
        db.commit()
        db.refresh(notification)

    except Exception:
        db.rollback()
        raise

    return notification


# ============================================================
# MARK NOTIFICATION FAILED
# ============================================================

def mark_notification_failed(
    db: Session,
    notification_id: str,
    error_message: str,
    provider: str | None = None,
) -> Notification | None:

    statement = (
        select(Notification)
        .where(
            Notification.id ==
            notification_id
        )
    )

    notification = (
        db.execute(statement)
        .scalar_one_or_none()
    )

    if notification is None:
        return None

    notification.status = "FAILED"

    notification.provider = provider

    notification.error_message = (
        error_message[:2000]
        if error_message
        else "Notification delivery failed."
    )

    notification.updated_at = (
        datetime.now(timezone.utc)
    )

    try:
        db.commit()
        db.refresh(notification)

    except Exception:
        db.rollback()
        raise

    return notification


# ============================================================
# GET SOS NOTIFICATIONS
# ============================================================

def get_sos_notifications(
    db: Session,
    user_id: str,
    sos_id: str,
) -> list[Notification]:

    statement = (
        select(Notification)
        .where(
            Notification.sos_id == sos_id,
            Notification.user_id == user_id,
        )
        .order_by(
            Notification.created_at.asc()
        )
    )

    return list(
        db.execute(statement)
        .scalars()
        .all()
    )